### ISSUE TITLE
Add documentation for relevant items

### ISSUE THREAD

**Issue by joeyfigaro** [bbfh-dev/bubblellaneous-pack#1]
Thank you for taking the time to publish this! The items look really interesting–especially the pin code lock. Unfortunately, interacting with it doesn't really do anything except print an ascii keypad in chat. Is the keypad on the lock not interactive?

**Comment by bbfh-dev** [comment]
**Hello there!** All items from the "Security" category are 100% interactive. In order to set/enter PIN you need to use the keyboard in chat:

![pincode-lock](https://i.ibb.co/chhsDqV/image.png)

Be aware, that the keyboard might not give any sort of feedback, because chat doesn't allow for changing messages, and spamming the chat wouldn't be nice either.

Enter the code and then press "[OK]", you will get a feedback message saying whether you entered the valid password or whether you have locked the PIN-Code lock.
