### ISSUE TITLE
Bubble Bench placement issues

### ISSUE THREAD

**Issue by SuperSinfire** [bbfh-dev/bubblellaneous-pack#18]
Hello there. I recently added your awesome data pack to my server and encountered a problem with the bench. Trying to create the Bubble bench by throwing a glass bottle on the crafting table did not work. I used the /give item function to add one to my bag which worked but when I placed this, it looked like a stone button on an item frame with no GUI upon clicking on it and there was no way to destroy the block unless in creative mode. I also could not see any furniture items on the creative menu. I have made sure the resource pack and data pack installed are the correct version v2.1.4.

Minecraft version 1.21.1

**Comment by bbfh-dev** [comment]
Are you using vanilla minecraft?

**Comment by SuperSinfire** [comment]
Yes, it is Vanilla Minecraft. It may also be worth noting that the /function menu:bubblellaneous does not work also. Is this just an issue with vanilla?

**Comment by bbfh-dev** [comment]
The datapack works fine on my end on vanilla 1.21.1, which is why I was asking.

1. Try using the datapack in singleplayer if you were using it on a server before.
2. Feel free to send screenshots of `/datapack list`
3. check that when you `/reload` server sends a message in chat (I don't remember what message it is, but it will look like "[Server] <something here"
